GET http://localhost:3001/api/blogs

###

POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "author": "sample",
    "url": "fakeurl.com",
    "title": "fake title",
    "likes": 2
}

###

DELETE http://localhost:3001/api/blogs/7

###

PUT http://localhost:3001/api/blogs/5 
Content-Type: application/json

{
    "likes": 2
}

###

POST http://localhost:3001/api/users
Content-Type: application/json

{
    "name": "sample",
    "username": "sampleusername3@fake.com"
}

###

PUT http://localhost:3001/api/users/sampleusername 
Content-Type: application/json

{
    "username": "smample"
}

###

GET http://localhost:3001/api/users

###