POST http://localhost:3001/api/blogs 
Content-Type: application/json

{
    "title": "a blog 2",
    "author": "no one 2",
    "url": "fake 2",
    "likes": 1
}

###

GET http://localhost:3001/api/blogs 
Content-Type: application/json

###

POST http://localhost:3001/api/blogs 
Content-Type: application/json

{
    "author": "no one 2",
    "likes": 1
}

###

POST http://localhost:3001/api/users
Content-Type: application/json

{
    "username": "fakeUser7",
    "name": "I do not exist",
    "password": "fa"
}

###

GET http://localhost:3001/api/users
Content-Type: application/json